# Generated by Django 5.2.9 on 2026-01-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_task_priority_alter_task_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.task')),
            ],
            bases=('projects.task',),
        ),
        migrations.CreateModel(
            name='MultiTeamProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('tasks', models.ManyToManyField(to='projects.task')),
                ('teams', models.ManyToManyField(to='projects.team')),
            ],
        ),
    ]
