# Generated by Django 5.2.9 on 2026-01-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_grouptask_task_ptr_grouptask_gt_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouptask',
            old_name='GT_title',
            new_name='gt_title',
        ),
    ]
