# Generated by Django 5.2.9 on 2026-01-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_gt_title_grouptask_gt_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupTask',
        ),
    ]
